name: mentor_app
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
